version: "3.8"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - dataset:/usr/api
  api:
    container_name: ebapi
    build:
      context: ./energybot
    depends_on:
      - db
    ports:
      - 3001:3001
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    volumes:
      - dataset:/usr/api
  client-vue:
    stdin_open: true
    environment:
      VUE_APP_BACKEND_URL: http://localhost:3001
      NODE_ENV: development
    ports:
      - 3000:80
    build:
      context: ./dbclient-vue
    volumes:
      - ./dbclient-vue:/app

volumes:
  db:
  dataset:
